---
title: DESCEND
timezone: UTC
collections:
  portfolio-items:
    title: Portfolio Items
    output: true
    permalink: portfolio
    images:
    - 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: rdiscount
pygments: true
name: So Far Swell
description: 
url: http://sofarswell.com
